port: 8026
handlers:
  - wurfl: hrb.handlers.wurfl_handler.simple.SimpleWurflHandler

wurfl:
  # All keys in Memcached are prefixed with this
  cache_prefix: hrb
  cache_lifetime: 100

  # Connect to Memcached with the following parameters
  memcached:
    host: localhost
    port: 11211
