from django.conf.urls.defaults import patterns, url, include
from ummeli.vlive.forms import SkillWizardForm, SkillWizardFormPick
from ummeli.vlive.profile import views
from ummeli.vlive.utils import pin_required
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.conf import settings


urlpatterns = patterns('',
    url(r'^$', views.profile, name='profile'),
    url(r'^(?P<user_id>\d+)/$', views.profile_view, name='profile_view'),
    url(r'^connections/$', views.my_connections, name='my_connections'),
    url(r'^connections/(?P<user_id>\d+)/$', views.connections, name='connections'),
    url(r'^connections/add/(?P<user_id>\d+)/$', views.add_connection, name='add_connection'),
    url(r'^connections/requests/$', views.connection_requests, name='connection_requests'),
    url(r'^connections/confirm/(?P<user_id>\d+)/$', views.confirm_request, name='confirm_request'),
    url(r'^connections/reject/(?P<user_id>\d+)/$', views.reject_request, name='reject_request'),

    url(r'^connections/add_by_industry/$',
        views.add_connection_by_industry,
        name='add_connection_by_industry'),
    url(r'^connections/add_by_industry/(?P<industry>\d+)/(?P<province>\d+)/$',
        views.add_connection_by_industry_result,
        name='add_connection_by_industry_result'),
    url(r'^connections/add_by_industry/(?P<industry>\d+)/(?P<province>\d+)/page/(?P<page>\d+)/$',
        views.add_connection_by_industry_result,
        name='add_connection_by_industry_result'),

    url(r'^connections/add_by_first_name/$',
        views.add_connection_by_first_name,
        name='add_connection_by_first_name'),
    url(r'^connections/add_by_first_name/(?P<province>\d+)/$',
        views.add_connection_by_first_name_result,
        name='add_connection_by_first_name_result'),
    url(r'^connections/add_by_first_name/(?P<province>\d+)/page/(?P<page>\d+)/$',
        views.add_connection_by_first_name_result,
        name='add_connection_by_first_name_result'),

    url(r'^connections/add_by_surname/$',
        views.add_connection_by_surname,
        name='add_connection_by_surname'),
    url(r'^connections/add_by_surname/(?P<province>\d+)/$',
        views.add_connection_by_surname_result,
        name='add_connection_by_surname_result'),
    url(r'^connections/add_by_surname/(?P<province>\d+)/page/(?P<page>\d+)/$',
        views.add_connection_by_surname_result,
        name='add_connection_by_surname_result'),

    url(r'connections/(?P<user_id>\d+)/jobs/$',
        pin_required(login_required(views.ConnectionJobsListView.as_view())),
        name='connection_jobs'),
    url(r'connections/(?P<user_id>\d+)/jobs/(?P<pk>\d+)/$',
        pin_required(login_required(views.ConnectionJobsDetailView.as_view())),
        name='connection_jobs'),

    url(r'^personal/$',
        pin_required(login_required(views.PersonalDetailsEditView.as_view())),
        name='edit_personal'),
    url(r'^contact/$',
        pin_required(login_required(views.ContactDetailsEditView.as_view())),
        name='edit_contact'),
    url(r'^about_me/$',
        pin_required(login_required(views.PersonalStatementEditView.as_view())),
        name='edit_about_me'),
    url(r'^education/$', views.education_details, name='edit_education'),

    url(r'certificates/$',
        views.CertificateListView.as_view(),
        name='certificate_list'),
    url(r'certificates/(?P<pk>\d+)/$',
        pin_required(login_required(views.CertificateEditView.as_view())),
        name='certificate_edit'),
    url(r'certificates/new/$',
        pin_required(login_required(views.CertificateCreateView.as_view())),
        name='certificate_new'),
    url(r'certificates/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.CertificateDeleteView.as_view())),
        name='certificate_delete'),

    url(r'work_experiences/$',
        pin_required(login_required(views.WorkExperienceListView.as_view())),
        name='work_experience_list'),
    url(r'work_experiences/(?P<pk>\d+)/$',
        pin_required(login_required(views.WorkExperienceEditView.as_view())),
        name='workExperience_edit'),
    url(r'work_experiences/new/$',
        pin_required(login_required(views.WorkExperienceCreateView.as_view())),
        name='workExperience_new'),
    url(r'work_experiences/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.WorkExperienceDeleteView.as_view())),
        name='workExperience_delete'),

    url(r'languages/$',
        pin_required(login_required(views.LanguageListView.as_view())),
        name='language_list'),
    url(r'languages/(?P<pk>\d+)/$',
        pin_required(login_required(views.LanguageEditView.as_view())),
        name='language_edit'),
    url(r'languages/new/$',
        pin_required(login_required(views.LanguageCreateView.as_view())),
        name='language_new'),
    url(r'languages/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.LanguageDeleteView.as_view())),
        name='language_delete'),

    url(r'references/$',
        pin_required(login_required(views.ReferenceListView.as_view())),
        name='reference_list'),
    url(r'references/(?P<pk>\d+)/$',
        pin_required(login_required(views.ReferenceEditView.as_view())),
        name='reference_edit'),
    url(r'references/new/$',
        pin_required(login_required(views.ReferenceCreateView.as_view())),
        name='reference_new'),
    url(r'references/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.ReferenceDeleteView.as_view())),
        name='reference_delete'),

    url(r'jobs/$',
        pin_required(login_required(views.MyJobsListView.as_view())),
        name='my_jobs'),
    url(r'jobs/(?P<pk>\d+)/$',
        pin_required(login_required(views.MyJobsEditView.as_view())),
        name='my_jobs'),
    url(r'jobs/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.MyJobsDeleteView.as_view())),
        name='my_jobs_delete'),

    url(r'mywork/$',
        pin_required(login_required(views.SkillListView.as_view())),
        name='skills'),
    url(r'mywork/(?P<pk>\d+)/$',
        pin_required(login_required(views.SkillsEditView.as_view())),
        name='skills'),
    url(r'mywork/delete/(?P<pk>\d+)/$',
        pin_required(login_required(views.SkillDeleteView.as_view())),
        name='skills_delete'),

    url(r'mywork/new/$',views.add_skill,
        name='skills_new'),
    url(r'mywork/new/(?P<skill_id>\d+)/$',views.add_skill_from_list,
        name='skills_new'),
    url(r'mywork/primary/(?P<skill_id>\d+)/$',views.mark_skill_as_primary,
        name='skills_primary')
)
